{
  parserClass="homeworkstudios.language.parser.VoxaScriptParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="VoxaScript"
  psiImplClassSuffix="Impl"
  psiPackage="homeworkstudios.language.psi"
  psiImplPackage="homeworkstudios.language.psi.impl"

  elementTypeHolderClass="homeworkstudios.language.psi.VoxaScriptTypes"
  elementTypeClass="homeworkstudios.language.psi.VoxaScriptElementType"
  tokenTypeClass="homeworkstudios.language.psi.VoxaScriptTokenType"

  psiImplUtilClass="homeworkstudios.language.psi.impl.VoxaScriptPsiImplUtil"
}

default ::= DEFAULT_FUN
number ::= NUM
string ::= TEXT
comma ::= COMMA_SEP
blockstart ::= BLOCK_START
blockend ::= BLOCK_END
paramstart ::= PARAM_START
paramend ::= PARAM_END
codeblock ::= CODE_BLOCK
mathop ::= MATH_OPERATOR

VoxaScriptFile ::= item_*

private item_ ::= (var|COMMENT|CRLF)

var ::= (VAR_TOKEN VAR_CHARACTER EQUALS VALUE? SEMICOLON)



property ::= (KEY? SEPARATOR VALUE?) | KEY {
  mixin="homeworkstudios.language.psi.impl.VoxaScriptNamedElementImpl"
  implements="homeworkstudios.language.psi.VoxaScriptNamedElement"
  methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}
